### ISSUE TITLE
Team Formation

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/Comrad#1]
### Form a team of 2 to 5 people

Gather with at least one other person to create a team around an idea or a problem that's interesting to you.

Spend a few minutes asking these questions:

- What's our shared vision?
  - Talk about what goal you want to accomplish as a team.

- What's in it for me?
  - Talk about each individual's motivation - what do you as an individual want to learn or accomplish?

- What talents do we bring to the table?
  - Share a bit of your experience and skills

- Set working agreements
  - What agreements do you, as a team, want to make for the time you are spending together?
  - Suggestions:
    - Show Up On Time
    - Agree on when you'll meet
    - "Art of the Possible" - no idea is stupid, let's consider everything.
    - Be Present - when you're here, you're here, be intentional with your time.

That's it! Now you have a clear goal for your team to accomplish and you know why each of you are here.

**Comment by dzimmerman902** [comment]
### Vision

Our shared vision is to develop a free/open source software to local community radios  and help them achieve their needs when regulatory needs, program setting, etc.

### Individual Motivation

Sean:

Devin: My motivation is to bring a good, clean quality product that I can be proud to present on a resume for job opportunities.

Hugo: My motivation is to learn building a project using the latest technologies like node.js, react and mongo db.

### Talents Brought

Sean:

Devin: I am very comfortable with the MERN stack. I want to teach fellow members on how to utilize it in the most efficient manner.

Hugo:  I bring front-end and design skills. As well as eagerness to help with the back-end technologies.

### Working Agreements

We agree to meet every Monday when possible at Galvanize. Our goal is to meet on time and devote our resources for developing the project. We are open to ideas and collaboration, no idea is stupid. Embrace a culture of learning and friendless.
