### ISSUE TITLE
Determine how to display custom HTML on screens like login screen

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#104]
Do we just have stations edit the installation?

**Comment by ogdenstudios** [comment]
I'd like to take a crack at this if that's cool. I'll assign to myself for now and touch base with y'all on Monday about more details. Let me know if we're any further along in terms of figuring this out.

**Comment by seankwilliams** [comment]
@ogdenstudios that would be great. I don't have much on this from a product requirements standpoint, so if you want to make some suggestions I'd appreciate it! The goal is to give stations a place where they can add any custom content they'd want to add (announcements, reminders, etc.) Doesn't necessarily have to be on the login screen too, so I'm open to any suggestions.

**Comment by ogdenstudios** [comment]
Recap from our conversation this evening: 

We're going to mostly limit this to uploading custom logos and choosing 2 brand colors for accent colors throughout. 

Sean wanted to make sure there was an ability to add some HTML in things like alerts and such for station wide announcements. I think that's most likely a functionality to get built into the alerts Christian is working on. 

I'll take this and solve for: custom logos and brand color selection and we can hammer out the rest later.

**Comment by seankwilliams** [comment]
Closing this out: the Calendar Agenda component we'll build in #498 will address KGNU's business need for this, though in a different way than including custom HTML would. We'll open another issue for this if a need for custom HTML comes up on any other page.
