### ISSUE TITLE
Front-End Validation

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#113]
Right now, there is no validation on the front-end of the login fields. We should set up the following validation:

1. If the user enters an invalid email address, display a message saying "Please enter a valid email address."
2. If the user does not provide an email address at all, display a message saying "Please enter a valid email address."
3. If the user does not provide a password at all, display a message saying "Please enter a valid password."
4. If the user does not enter a username and password that matches valid login credentials, display a message saying "The username and/or password you entered is incorrect. Please try again."

Check with Devin before starting on this task. He was wondering if we could use tv4/StateValidator to do this.

**Comment by dzimmerman902** [comment]
#210 added these features

**Comment by dzimmerman902** [comment]
Still need to fix some of the front end validation

**Comment by dzimmerman902** [comment]
I believe it's all good
