### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by msiadak** [codefordenver/Comrad#115]

**Comment by msiadak** [comment]
We should research the pros and cons of different deployment strategies for Comrad.

Options and technologies to think about:

* Docker / Docker Compose
* Cloud platform pricing /cost estimating (AWS/Azure/GCP)
* Other hosting platforms (now/heroku)

**Comment by dzimmerman902** [comment]
I'll do the research for the Heroku part

**Comment by dzimmerman902** [comment]
comrad.herokuapp.com is broke

**Comment by seankwilliams** [comment]
Closing this for now - we will figure out a specific deployment strategy with KGNU, and then a separate deployment strategy for cloud hosting in #162
