### ISSUE TITLE
Validation API

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#126]
# Guidelines

Have a short descriptive title <br>
Make sure to click the following:

- [x] Assignees
- [x] Labels
- [x] Milestone

# Full Details

Working on the authentication process for the front and back end. Everything seems to be working correctly but I seem to be getting an error when navigating to a HOC (higher order component). 

![screen shot 2018-09-13 at 11 11 32 am](https://user-images.githubusercontent.com/18602363/45503998-d17c2280-b745-11e8-82af-6ccad8c6332c.png)

I believe it's how I have it set up in the HOC but it's conflicting with React's way of doing things. Would love to get some help on this.

For the most part, everything works as it should in regards to authentication goes for signing in and out.

**Comment by msiadak** [comment]
Will take a look this evening
