### ISSUE TITLE
401 Unauthorized Component

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#132]
# Guidelines

Have a short descriptive title <br>
Make sure to click the following:

- [ ] Assignees
- [x] Labels
- [ ] Milestone

# Full Details

Would like a simple component to display is a user tries to access a page they are not authorized to get too.

**Comment by ogdenstudios** [comment]
Image from Lauren: 
![comrad3-12](https://user-images.githubusercontent.com/29899554/48038529-465c4f00-e12e-11e8-94af-bee3df556706.png)
