### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#139]
Build a Search Bar component for the music library. The component should have a search box on one line and then four filters on the next line: "All" "Artists" "Albums" "Songs". Only one filter can be selected at a time, and the selected filter should be designated with an underline.

Wireframe at: https://drive.google.com/file/d/1Kk1qHuS-fNra4_emvOoQcK_BRkqqtSrA/view

**Comment by dzimmerman902** [comment]
Most of the inputs are work the same. I made a component that can take in a prop to determine a search icon. As long as it's wrapped in a form, you can choose what action to use.

**Comment by seankwilliams** [comment]
resolved by #278
