### ISSUE TITLE
My Past Shows

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#142]
Build the My Past Shows Component

Design at https://drive.google.com/file/d/1CFzsCRxv9YChrKXGWt63kjgVuwEffftL/view

**Comment by ogdenstudios** [comment]
Can we merge this with #141? Wondering if the grid of shows could be one discrete component with different props passed in

**Comment by ogdenstudios** [comment]
Woop - I mean #140

**Comment by ogdenstudios** [comment]
Merged with #160
