### ISSUE TITLE
Permissions Schema/API

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#163]
The Create/Edit user API endpoints should be able to adjust the permissions for each user. The permissions will be exposed in high-level roles like "DJ" or "Music Director", and users can have multiple roles.

**Everyone**
- Can view show calendar, Show Builder, and music library.

**DJ**
•	Can modify their own shows in Show Builder
•	Can modify the description for their own shows
•	No other edit permissions

**Underwriting**
•	Can add/edit traffic calendar
•	Can run reports

**Show Captain** 
•	Can add/edit show calendar 
•	Can add/edit all shows in Show Builder

**Music Library Admin**
•	Can modify records in the music library

**Full Access**
•	Can add/edit everything except users and change Comrad settings (like whether it’s a reporting period)
•	Can run reports

**Admin**
•	Same as Full Access, but can also:
    o	Add/edit users
    o	Change Comrad settings (like whether it’s a reporting period)

Side note: the same permissions will be used for API tokens

**Comment by dzimmerman902** [comment]
@seankwilliams Passing this off to you to tweak inside of accessControl. Let me know if you have any questions on how this works!
