### ISSUE TITLE
Get Users endpoint: return data on whether the user can be deleted

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#166]
The Users List has either a Deactivate or Delete link for each user. Users that are hosting any show instances (past, present or future) associated with them in the database cannot be deleted, only deactivated.

Return a can_delete boolean (or something similar) with the Get Users function that flags whether the user is deletable. (If they are not deletable, the UI will display a "Deactivate" link instead of a "Delete" link)

**Comment by dzimmerman902** [comment]
@seankwilliams Hey Sean, what would you recommend as a good way to detect if users are hosting a show?

**Comment by seankwilliams** [comment]
@dzimmerman902 You can check the show collection for a record with show_details.host matching the user's id!
