### ISSUE TITLE
Delete User endpoint: do not allow deleting a user with associated data

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#167]
This is related to #166

If you try to delete a user via the Delete User endpoint and that user is marked as the host of any show (past or present), the API endpoint should return a 422 status code with an error message saying the user cannot be deleted.

**Comment by dzimmerman902** [comment]
@seankwilliams This is finished

**Comment by seankwilliams** [comment]
awesome, thanks @dzimmerman902 !
