### ISSUE TITLE
API Tokens - Schema and access

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#169]
Set up the application to use API tokens. The APIs for the application can be accessed externally by APIs. Use cases for this include integrating Comrad with other radio systems or JavaScript widgets that could go on a station's public site (for example, to display what show is currently playing)

API tokens will have specific permissions -- the same permission levels that are available to users, as described in #163. 

API tokens should be SHA256 hashed when they are stored in the database. The first six characters of an API token should be stored in a separate field, unencrypted, so they can be displayed to users on the front-end.

API tokens should contain this data:
- Name (will be exposed in the manage API tokens interface within Comrad, so this is a human readable name for identification purposes only
- Hashed API key
- First six characters of API key
- Last use date/time
- Permissions
- Active/inactive (boolean)

The last use date/time should be updated whenever the API token is used.

After this is done, we can create more Waffle tasks that involve the API endpoints to manage API tokens and the UI to manage API tokens.

**Comment by dzimmerman902** [comment]
Working on these with branch devin/feature/api-key

**Comment by dzimmerman902** [comment]
@seankwilliams I believe this is complete, the only thing is I have a question in regards to status. I sent it to you in discord which I can update without having to make a new issue ticket.
