### ISSUE TITLE
Add automated linting and formatting to project

### ISSUE THREAD

**Issue by msiadak** [codefordenver/Comrad#212]
# Description of Issue

What does the rest of the team think about adding automated linted and code formatting to the project?  I use these utilities on all of my personal projects and find that they have a lot of benefits to readability and correctness.

We could add npm scripts for these and (possibly) add them to precommit or prepush git hooks.

# Possible Solution and/or Approach

I recommend that we use [eslint](https://eslint.org/) for linting and [prettier](https://prettier.io/) for formatting.

I could implement this in a short amount of time if we agree that this is something to pursue.

# Approval?

_Leads Comment Below_

**Comment by dzimmerman902** [comment]
@msiadak Great idea! I went ahead and pushed up a branch called 212-linting. Feel free to pull that branch, I've added a .eslint.json file with some starter settings, I found these work best with React. Don't hesitate to add/change anything that you feel would help benefit it. Thanks!
