### ISSUE TITLE
Research for ElasticSearch

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#214]
# Description of Issue

Mike mentioned adding elastic search to our MongoDB queries for faster results. This will a great implementation because of how large our library collections are going to be.

# Possible Solution and/or Approach

https://www.elastic.co/

# Approval?

_Leads Comment Below_

**Comment by seankwilliams** [comment]
Closing this - a text index in Mongo does the trick instead of ElasticSearch!
