### ISSUE TITLE
Drag & Drop Feature for React

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#215]
# Description of Issue

One feature for our application is the ability to drag and drop elements inside of the DOM and trigger events based on it. Similar to how a trello/waffle page works. 

# Possible Solution and/or Approach

Nothing right now, need to do some research

# Approval?

_Leads Comment Below_

**Comment by msiadak** [comment]
People seem to like this one:
https://github.com/atlassian/react-beautiful-dnd
