### ISSUE TITLE
Implement Color Palette across app

### ISSUE THREAD

**Issue by ogdenstudios** [codefordenver/Comrad#221]
# Description of Issue

We've chosen six colors and need to implement them throughout the app. 

# Possible Solution and/or Approach

These likely make sense to go in a _variables.scss file. The color palette is as follows: 

- Themeable Color 1 - #007283
- Themeable Color 2 - #7DB2BF
- Default Dark Gray - #555759
- Default Medium Gray - #A4A9AD
- Default Light Gray - #DBDCDD
- Default White - #FFFFFF

Themeable color 1/2 are meant to be customized by individual stations

**Comment by dzimmerman902** [comment]
Closing for now
