### ISSUE TITLE
Custom Properties for Shows

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#242]
Display custom properties for shows on the Edit Instance popup. Also, set up a way to configure these per station. (see schema requirements at https://docs.google.com/document/d/1m8KZpaeIRVVkjn6bVqa__LBmavn1L2H4w9l-mW3qfEc/edit)

**Comment by dzimmerman902** [comment]
@jberns Do we need to keep this issue open or do we have another one for it?
