### ISSUE TITLE
Show Calendar: Add/Edit Show Instance popup

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#243]
Build the Add Edit/Show Instance popup (page 7 of https://docs.google.com/document/d/1m8KZpaeIRVVkjn6bVqa__LBmavn1L2H4w9l-mW3qfEc/edit)

**Comment by dzimmerman902** [comment]
@jberns Do we need to keep this issue open or do we have another one for it?

**Comment by seankwilliams** [comment]
This is done
