### ISSUE TITLE
Side Nav Bar

### ISSUE THREAD

**Issue by msiadak** [codefordenver/Comrad#265]
## Description of Issue

The Sidebar component needs some love -- the icons are all broken now due to our migration away from using the fontawesome css classes. 

## Possible Solution and/or Approach

Re-add SVG icons following our new icon approach.  Tooltip component is nearly done, so I think we can also add tooltips and wire up the sidebar items to routes.

**Comment by seankwilliams** [comment]
@msiadak Is this done now? If so, can you close it out?

**Comment by dzimmerman902** [comment]
This is done
