### ISSUE TITLE
Dropdown component - create an option for menu to open on the right

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#282]
The wireframe at https://drive.google.com/file/d/10PNXLQ9ypRs_stgtDLx1bG5gZxzlnbzu/view?usp=sharing shows the "Add" dropdown on the Music Library main page with the menu opening on the right side of the button. However, on http://localhost:3000/library/search the menu opens below the button. 

Please add an option to the Dropdown component that will allow the menu to open on the right side of the button. The default option for the component should still be that the menu appears below the dropdown, but you should be able to pass a property into the Dropdown component that makes the menu open on the right.

Please set the property on the Music Library main page and Users main page so that the menu opens on the right of the Add button.

**Comment by seankwilliams** [comment]
@dzimmerman902 Did you get this one done in your work on https://github.com/codefordenver/Comrad/pull/411?

**Comment by ehirshfield** [comment]
@seankwilliams is the Users main page direction in this ticket outdated? I don't see a dropdown button on it

**Comment by seankwilliams** [comment]
@ehirshfield yep, the mention of Users in this ticket is outdated. So just changing the Music Library page is good. Reviewing your PR now!
