### ISSUE TITLE
Add Track

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#296]
depends on #291

Add an "Add" button to the View Album page that lets you add a track to the album

- The Add button should use a Dropdown component with text of "Add Track"
- When clicking the Add Trackbutton, the user should go to a page that has a form to add the track, using React Form
- The user should receive a validation error if they try to add a track that has the same track number and disk number as another track on the same album
- The disk number should default to the maximum disk number used on the album
- The track number should default to n + 1, where n is the highest track number on the maximum disk number used on the album
- When the user submits the form successfully, they should be returned to the album

**Comment by kmid5280** [comment]
@seankwilliams I'm taking a look at this issue. A few questions - one, where is the View Album page? Is this where you click on the library, click "albums" under the search bar, and then click on the individual album under there? Two, will this require implementing a new page, i.e. an add track page specific to the album view page?

**Comment by seankwilliams** [comment]
@kmid5280 

_where is the View Album page? Is this where you click on the library, click "albums" under the search bar, and then click on the individual album under there?_

Yep! Or, you can also get to it by clicking an artist and then, on that artist's page, clicking on an album.

_Two, will this require implementing a new page, i.e. an add track page specific to the album view page?_

Yes, this will. The page will be one single template and take the album ID as a parameter.

**Comment by kmid5280** [comment]
@seankwilliams Is there a particular page the add track page can be modeled after?

**Comment by seankwilliams** [comment]
@kmid5280 Yes, I would look to the Add Artist page for an example.

**Comment by kmid5280** [comment]
@seankwilliams So it looks like the add artist page imports a separate form component. I take it the same thing will have to happen here?

**Comment by seankwilliams** [comment]
@kmid5280 yes, and building that component is part of this task

**Comment by kmid5280** [comment]
@seankwilliams Will I have to set up a new set of actions and reducers in the redux folder, i.e. a "tracks" directory, or will I simply be adding these into an existing one such as the "album" ones?

**Comment by seankwilliams** [comment]
@kmid5280 I can't remember the code specifics so I'm not sure off the top of my head, please move forward with whatever you think is best and we will address the location when we do the pull request if it should be somewhere else.

**Comment by kmid5280** [comment]
@seankwilliams Ok. I put together a basic framework of actions and reducers as well as the component and form. I'm probably not correct though on how my actions are set up and might need some help understanding what needs to go in there. Obviously I need an "add track" action but do I need anything else that will fetch data or perform other functions? I'm also aware that this has to be posted to the album by id, so will need to see how exactly that gets passed in.

**Comment by seankwilliams** [comment]
@kmid5280 okay great! That's pretty broad so let's narrow in on specific pieces and take things one at a time. 

For passing in an ID, you'll want to take a look at how that's handled on other pages. `client\src\routes\LibraryRoutes\LibraryRoutes.js` is a good place to start. Please take a look and read an introduction to React Router and see if you understand how the id is being passed to each page. Then, I would aim for an intermediate goal. I'd aim for just this piece of the requirements at first:

- The Add button should use a Dropdown component with text of "Add Track"
- When clicking the Add Track button, the user should go to a page

On that page, use `console.log` to confirm that you have the album ID accessible in the `formTrackAdd` component's `state` or `props`.

**Comment by kmid5280** [comment]
@seankwilliams I have been working on it and am still trying to see how all of this fits together.

I'm assuming the following:
-Put a dropdown component in the AlbumViewPage. For instance `<Dropdown type="button" text="Add Track" to='library/track/add' />`
-Add the library/track/add endpoint in LibraryRoutes.js, which points to the TrackAddPage component. Thus when the dropdown component is clicked on it directs to that component via the router.

Is this correct so far?

In trying this I am having some trouble getting the Dropdown component to link to the TrackAddPage component. It wants to drop down a menu instead and won't take me to the page when clicking on it.

**Comment by seankwilliams** [comment]
@kmid5280 Ah, gotcha. You know, the `Dropdown` component may not actually support linking to something without a dropdown menu. So, can you open up the `Dropdown` component and see if the components that make the toggle button for the dropdown could be reused for the link instead? You will probably have to modify them to take a `to` property, since I'd bet they aren't set up to do that.

**Comment by kmid5280** [comment]
@seankwilliams Are you suggesting modifying the Dropdown component, or passing in different values to the component from the parent?

Do we really need to use the Dropdown component at all? Since we just need to click it and have it take us to another component, maybe there's a simpler way to do it.

**Comment by seankwilliams** [comment]
@kmid5280 Hm, no that's not what I'm saying so I'm not sure this part was clear: _can you open up the Dropdown component and see if the components that make the toggle button for the dropdown could be reused for the link instead?_ I mean that you should look for an alternative to the `Dropdown` component, and a good place to start would be seeing if we can reuse the components that make up the toggle button/link within `Dropdown`'s component, since that will have the same UI as this button. DOes that make sense?

**Comment by kmid5280** [comment]
@seankwilliams Would you suggest in that case simply building a new component, like a AddTrackButton component, that maintains a lot of the same functionality as the Dropdown?

**Comment by seankwilliams** [comment]
@kmid5280 What do you think is the best approach? I don't have a suggestion, I've only been trying to point out areas of the code you could review while deciding what to do.

**Comment by kmid5280** [comment]
@seankwilliams One workaround might be to just make a div and style it to look like the Dropdown component. It's basically just a link.

**Comment by seankwilliams** [comment]
@kmid5280 great, if you think that's the best route, let's go with that!

**Comment by kmid5280** [comment]
@seankwilliams So far I have a clickable Link on the AlbumViewPage. If you click the link it shows the AddTrackPage, and the console.log will show the album id. Am I on the right track?

**Comment by seankwilliams** [comment]
@kmid5280 very nice, it's looking good so far!

**Comment by kmid5280** [comment]
@seankwilliams Okay good. Since you mentioned breaking this up into smaller chunks, what do you suppose a good next step is? Also, does everything look set up correctly so far, i.e. the endpoints and the route that I put in the library router?

**Comment by seankwilliams** [comment]
@kmid5280 here are some next steps:

1. Please style the Add Track button so it looks similar to the add button on the Music Library main page, and please position the button above the table of tracks.
2. Right now clicking Add Track is going to a page with a blank screen, so please start seeing if you can get the track page to display. A good place to start is checking the JavaScript errors on the page.
3. After #2, you'll want to make the form for adding a track appear on the page, with fields for each of the values that will be inserted.

**Comment by kmid5280** [comment]
@seankwilliams Sorry, I screwed up. Looks like I didn't commit one of the index files that exported the form, so that's why you're seeing a blank page. If you look at it now you should see what I'm seeing. Would you mind taking another look at it?

**Comment by seankwilliams** [comment]
@kmid5280 ah, got it. Okay, I've pulled the code now but the "Add Track" button is now making a form appear below the existing table, like so:

![add-track-form](https://user-images.githubusercontent.com/151931/57116633-a9145900-6d13-11e9-802a-d0e874435858.PNG)

Instead, the link should go to a page that has the Add Track form but not the album title + track table. To fix that, you'll want to look at how you have the `Switch` and `Route` components set up for your add page. I believe the issue is there, so you might have to research React Router a bit to find it.

Then, once that's done, please give numbers 1 and 3 a try from my comment above!

**Comment by kmid5280** [comment]
@seankwilliams I was able to get the add track link to go to its own page when clicked. Also I styled the link and moved it. Probably needs more work but how is it so far?

**Comment by seankwilliams** [comment]
@kmid5280 Nice, that's looking good. The next step is to clean up the formatting on this page and set up some default values. Here are some specific next steps:

- [ ] Copy some styles from the Add Artist page at `/library/artist/add` so that (1) the fields have a constraint on their width and aren't stretching across the whole screen and (2) the fields have vertical space in between them
- [ ] Split the "Duration" field into two fields, one with a label/placeholder of "Min" and another with a placeholder of "Sec". The fields should appear on the same line with a colon in between them and text saying "Duration" to the left.
- [ ] Pull data from the album to display a line that says "Album: [album name]" (w/o the quotes) below the header but above the fields. [album name] should be replaced with the name of the album.
- [ ] Pull data from the album to make the disk number default to the maximum disk number used on the album
- [ ] Pull data from the album to make the track number should default to n + 1, where n is the highest track number on the maximum disk number used on the album

**Comment by kmid5280** [comment]
@seankwilliams I'm trying to work on the third thing you mentioned, but I'm having some trouble getting the album name into the add track page. I can see where the album name is being passed into the album view page, it is passed into the props under album.doc.name, but that parameter is not showing up in the add track page. Do you have any suggestions?

**Comment by seankwilliams** [comment]
@kmid5280 good observation! The album data is all stored in the Redux store. I can't remember if you've used Redux before, so if not, you may want to read a little bit on it and install Redux dev tools. The `album` object is populated already, and in order to get the data for it in the `FormTrackAdd` component, you'll have to:

1. Create a `mapStatetoProps` function that will tell Redux which properties to bring from the Redux store into properties for the component:
```
function mapStateToProps({ album }) {
  return {
    album,
  };
}
```
2. Replace `null` with `mapStateToProps` in the first parameter of the `connect` function 

Then, the album will be available in `this.props.album` within the `FormTrackAdd` React component. Let me know if that works for you!

Also: if you browse the album data in the Redux store, you'll see a list of tracks, which you could probably use for the prefilled disk number/track number functionality.

**Comment by kmid5280** [comment]
@seankwilliams I think I was able to hit on all five points in your above comment. Some of this is admittedly a little messy and will probably need some cleanup. I put in some for loops in the render() section of the TrackAddPage to calculate and pass in the max disk number and max track number values. It works but I realize these should probably be moved to their own separate functions. If you have any suggestions on the best ways to do that or feel there's a better way I could have implemented these changes please let me know.

**Comment by kmid5280** [comment]
@seankwilliams I moved the function that calculates the max disk number and max track number to a lifecycle hook.

**Comment by seankwilliams** [comment]
@kmid5280 Excellent work! We won't worry about any code cleanup yet, let's get the last pieces in place and get things functional and then I'll look through the code when you've got a PR ready for review. Here's what's left:

- [ ] Please add a little more margin between the album name and Disk Number field so the "Disk Number" label isn't overlapping the album name
- [ ] The next step is to get the redux action working. Right now, submitting the form gives an error where `trackAdd` is undefined. Take a look at how `artistUpdate` is used in `\client\src\components\FormArtistUpdateName\FormArtistUpdateName.js` and see if you can get things working so the API call in `trackAdd` works
- [ ] Then, see if the API call works for the "happy path": in other words, when there wouldn't be any validation errors on the server-side (ie, the track does not have the same disk/track number as another track on the album). If the API doesn't work, you'll have to troubleshoot the server-side code.
- [ ] When the track is successfully added, navigate the user back to the Album page.
- [ ] Add validation errors to satisfy this requirement: "The user should receive a validation error if they try to add a track that has the same track number and disk number as another track on the same album" You can look at the `FormArtistUpdateName` component and it's supporting files (including the API endpoint it calls) for an idea of how to do this.

**Comment by kmid5280** [comment]
@seankwilliams Sad to say my progress on this is slow. I am able to call the trackAdd action now, but it returns an error - "Request failed with status code 404." I suspect maybe I have the wrong path set in the track actions, but what is the right path?

Also I need to work out specifically what actions I need to set up. I'm sure I will need the trackAdd action, but how will I know if other actions are warranted too?

**Comment by seankwilliams** [comment]
@kmid5280 I'm out of town and not back until Thursday so I'll get back to you in full then! In general, you'll want to check the server's route files to see what the right route is for the API to add a track. And as far as any other actions needed, look at how things are done on other parts of the application and see if you can understand them and determine if they're necessary for tracks. I'm not sure anything is needed other than trackAdd though.

**Comment by kmid5280** [comment]
@seankwilliams I am able to post tracks to the main track page, but I need to post them to the individual album. I can't find anything in the routers that mentions what path I need to use for this. I tried using /v1/albums/${id}/tracks, but that didn't work. Do you have any suggestions, or are there other components that do anything similar I can look at?

**Comment by kmid5280** [comment]
@seankwilliams I think I have the right path and can post tracks (if I post them they will appear in the library search page), but right now it is not associating them with the specific album. I have to pass in the album properties into the fields somehow, including the album id. Are there any other components that do anything similar that I can look at so that I can get a better idea as to how to do this?

**Comment by kmid5280** [comment]
@seankwilliams Should give an update - I looked at the track schema under the models and set up the track add form so that it passes in the artist and album IDs as values. For instance in the track schema it takes a parameter 'Album' with the album id as a value. Now the album and artist ids are being submitted along with the rest of the track information, however I still don't see them actually being listed on the album page itself. I'm going to go ahead and commit this, but I'm not sure if I'm on the right track.

**Comment by seankwilliams** [comment]
@kmid5280 You're very close with this! The problem here is that the parameters in your XHR request are not exactly matching the track model's names:

![xhr-request](https://user-images.githubusercontent.com/151931/58217405-f440dc80-7cbf-11e9-90c1-c00aa0340a2f.PNG)

Rather than `Artist`, the model has `artists`, and it's expecting an array of strings instead of a string. (This is for cases when a track has multiple artists, which we won't worry about in the scope of this issue.) And, rather than `Album`, the model has `album` (case-sensitive). Once you correct those, you'll want to change `disk-number` and `track-number` so they match the model naming as well.

Then, after that, you might find that the View Album page doesn't have the updated track list until you refresh the page. If that's the case (I don't know if it will be), you'll need to dispatch a Redux action that will reload the album data.

**Comment by kmid5280** [comment]
@seankwilliams Gotcha. I was going off of the refs in the track model. I adjusted it and it's posting tracks now. You might see a lot of test tracks in the library page (unless those are only visible on my machine) - if so, sorry for the spam.

In addition to submitting the form fields, I need to create another field that takes the minutes and seconds and converts them to the total of seconds, to get the duration_in_seconds value. Any idea how to calculate that after the form is submitted and include that in the values?

Also still working on getting the page to reload after submission.

**Comment by seankwilliams** [comment]
@kmid5280 awesome, glad you got it working! And no worries on the extra records, create as many as you need. That's what the dev database is for!

As for the form fields: before calling the API, you'll want to create the duration in seconds property in the information you're sending to the API. You'd do it by `minutes * 60 + seconds. I would put the track manipulation inside the handler for the `trackAdd` Redux action so that your logic will take effect any time the `trackAdd` function is used.

**Comment by kmid5280** [comment]
@seankwilliams I played around with it before I saw your comment, and was able to do this by putting it in the form's handleSubmit function. Would that work? I committed it if you want to look.

**Comment by seankwilliams** [comment]
@kmid5280 yep, manipulating the data in handleSubmit will work just fine! We can always move it into the Redux action at a later date if we need to share that logic between any components.

**Comment by kmid5280** [comment]
@seankwilliams Not finished yet, but so far I have added conditionals that return an error if there is already an existing track with the same disk and track numbers, as well as set the default disk and track numbers in the form to 1 if there are no existing tracks on the album. If you wouldn't mind taking a look, any feedback would be appreciated. Thanks!

**Comment by seankwilliams** [comment]
@kmid5280 great! Validating those changes on the front-end is okay. They will also need to be validated in the server's API endpoint though, so you'll want to add validaton there as well (in case someone is using the API directly). You can look at the API for updating artists to see examples of how that's done. (Check the `validateArtistData` function in `Comrad\server\v1\controllers\artists\update.js`)

**Comment by kmid5280** [comment]
@seankwilliams How do I access the track list from the api endpoint? I'm looking at server/v1/controllers/tracks/create.js . I can't see it from the db variable.

**Comment by seankwilliams** [comment]
@kmid5280 Good question. The track list isn't available in the API endpoint right now, so you'll have to use additional queries to validate the track data. So, you'll want to add a validateTrackData function that's similar to the validateArtistData function. Here's an example of how you'd check to see if there's a track with the same disk_number/track_number on the album:

```
db.Track.findOne({
  disk_number: **disk number from track you're inserting**,
  track_number: **track number from track you're inserting**,
  album: **albumId from track you're inserting**
})
.then(otherTrack => {
        if (otherTrack !== null) {
          throw 'There is already an track with this disk and track number on this album.';
        return data;
      })
      .catch(err => {
        console.log('thrown error:');
        console.log(err);
        throw err;
      });
```

Let me know if you want to schedule a screenshare and I can walk you through the validation a bit more! We can do a bit of the code together too since this involves some back-end Mongo querying work which I'm not sure you've worked in yet.
