### ISSUE TITLE
Change password page

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#303]
The "Change Password" link in #302 should lead to a page where the user can change their password.

The page should have:
- Password field (text box)
- Confirm Password field (text box)
- Submit button

Clicking the Submit button should change the users password, hide the form and display a message saying "Your password has been changed successfully."

The form should require both fields to have values, and the passwords must match. If not, an error message should be displayed.

Please use the same form library as the rest of the application to build this form.

**Comment by ehirshfield** [comment]
@seankwilliams would a route for this page be found in the `UserRoutes` or would this become a new folder called something like `ProfileRoutes`?

**Comment by dzimmerman902** [comment]
@ehirshfield Go ahead and put it in the UserRoutes for now

**Comment by dzimmerman902** [comment]
@ehirshfield @seankwilliams Also, if you decided to work on the API or any redux routes, please name it passwordChange

**Comment by ehirshfield** [comment]
@dzimmerman902 awesome! That's good to know
