### ISSUE TITLE
Reimplement Tooltip component using an existing library

### ISSUE THREAD

**Issue by msiadak** [codefordenver/Comrad#329]
## Description of Issue

My custom tooltip implementation is pretty limited and we're running into a lot of edge cases that are preventing it from being used effectively.  We talked and decided that we should replace it with an existing tooltip library that is already handling edge cases well.

## Possible Solution and/or Approach

Options:

* [react-tooltip](https://github.com/wwayne/react-tooltip)
* [rc-tooltip](https://github.com/react-component/tooltip)
* [reactjs-popup](https://github.com/yjose/reactjs-popup/)
* [react-hint](https://github.com/slmgc/react-hint)

## Approval?

**Comment by msiadak** [comment]
@jberns said he would do some testing to find a library that works well with his show calendar page use case

**Comment by jberns** [comment]
@msiadak I added 4 custom wrappers in the ShowCalendar.js folder based on some preliminary testing with all 4 libraries, so you can swap between them by changing the last number where eventWrapper is assigned.  I liked rc-tooltip the most and was the easiest to implement using component state to track the visibility.
