### ISSUE TITLE
Left menu issue: hover area on tooltip is incorrect

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#359]
Hover the mouse cursor over the area immediately to the right of the menu icons.

ACTUAL BEHAVIOR
The tooltip label appears, potentially blocking the ability to click on icons that might happen to be underneath the tooltip area

EXPECTED BEHAVIOR
The tooltip label should only appear if the user hovers over the icon itself.

The video at https://www.dropbox.com/s/7593yf89ze8pu8l/tooltip%20bug.mp4?dl=0 shows the incorrect behavior that is currently happening.

**Comment by jberns** [comment]
This will be fixed as part of issue #322.
