### ISSUE TITLE
Button - small size class

### ISSUE THREAD

**Issue by jberns** [codefordenver/Comrad#368]
- [ ] Update button css to have a small button class

See bootstrap for reference:
https://getbootstrap.com/docs/4.0/components/buttons/#sizes

**Comment by zenkbaries** [comment]
Im curious. I wanted to understand the problem and solution to this issue just for my own learning. 

I see that the class already has small button class (subclass) at line 20-26 of client/src/components/Button/_Button.scss
```ccs 
  &--small {
    font-size: 1.2rem;
    height: 3rem;
    padding: 0 1.4rem;
  }
```
Did I misunderstood the issue?

**Comment by dzimmerman902** [comment]
@zenkbaries Hey John! Great catch at finding the code for it. This is a closed issue meaning that most likely it's either been taken care of or was irrelevant. If you look above your comment, you can see a timeline of the different things that took place to get here.

Let me know if you have any other questions!
