### ISSUE TITLE
ButtonIcon Components

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#381]
## Description of Issue

Need a component that uses icons and that has the same functionality as the other ones.

## Possible Solution and/or Approach

**Icons Needs**
- [x] Pencil (primary color)
- [x] Check Mark (primary color)
- [x] X (danger color)

**Props Needed**
- [x] Icon

**Features**
- [ ] Loading should disable
- [ ] Loading should brighten color

## Approval?

_Leads Comment Below_

**Comment by seankwilliams** [comment]
I believe this is done, so closing this out!
