### ISSUE TITLE
TextArea Component

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#382]
## Description of Issue

Looking for a text area component that matches our style.

## Possible Solution and/or Approach

**Props**
- [ ] Redux Form Props (meta, etc.)

**Features**
- [ ] Error
- [ ] Validation

## Additional Comments

Look at the original Input component for inspiration on how to build it

**Comment by kmid5280** [comment]
I'd like to give this issue a try, but is there a way I can export this into another component (such as the Dashboard) to test it out? Thanks!

**Comment by jberns** [comment]
> I'd like to give this issue a try, but is there a way I can export this into another component (such as the Dashboard) to test it out? Thanks!

If you want to use the new show form (client/src/components/Shows/NewShow/Form.js), I had planned to use this for the Summary and Description fields and I can help you out if you need it.  The plan was set the <Field> component prop to "component={TextArea}" vs the current "component={Input}."
