### ISSUE TITLE
Checkbox Component

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#392]
## Description of Issue

Our checkbox component needs some love. It needs to be larger than the default and use our primary colors. It doesn't need to have any kind of flashy animation. 

## Possible Solution and/or Approach

**Props**
- [ ] className
- [ ] children

## Additional Comments

Must also be connected to redux form to capture the values. Provide examples in our styleguidist. Create basic tests for it as well.

**Comment by seankwilliams** [comment]
@kmid5280 You'll notice the checkbox component actually doesn't even have `type="checkbox"` right now, so it definitely needs some love! Please let me know if you have any questions on how this should look.

**Comment by seankwilliams** [comment]
Closing this out - this is done and merged to `development`!
