### ISSUE TITLE
Reusable SASS Grid

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#396]
## Description of Issue

Looking for some SASS code that we can use to implement some kind of quick grid system like bootstraps grid layout. Yes we can implement grid at anytime, but was looking for a mixins to boot up grid and then some additional classes to handle column width, etc.

## Possible Solution and/or Approach

Here is bootstraps version: https://getbootstrap.com/docs/4.3/layout/grid/
If you can find a SASS library already in existence, that would be great as well

## Additional Comments

_Comments Go Here_

**Comment by kmid5280** [comment]
@seankwilliams Do you think something like this might work? https://github.com/hugeinc/flexboxgrid-sass

**Comment by seankwilliams** [comment]
@kmid5280 can you let me know some details about the library? What are its strengths/weaknesses, and how does it compare to the bootstrap version linked to in the issue?

**Comment by kmid5280** [comment]
@seankwilliams If the bootstrap version will work with the project, I'm not sure there are any advantages or disadvantages that stand out either way. They both seem pretty straightforward. Are you just researching which code to go with or trying to implement it as well?

**Comment by dzimmerman902** [comment]
@seankwilliams @kmid5280 This is probably a ticket I created to create some reusable code from scratch. There are definitely other resources out there that work well with react (react-bootstrap-grid, something like that). I'm ok with closing this ticket.

**Comment by seankwilliams** [comment]
Thanks @dzimmerman902 and @kmid5280 ! Closing this out.
