### ISSUE TITLE
No Table Display for No Data

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#403]
## Description of Issue

@seankwilliams 

What do you think about having some kind of message when there is no data? Instead of having an empty table, maybe have some kind of clean component that essentially has a custom message when there is no data. 

I believe the LargeText component does the trick, maybe we can incorporate it?

## Possible Solution and/or Approach

- [ ] React Component
- [ ] Message Props

## Additional Comments

N/A

**Comment by seankwilliams** [comment]
@dzimmerman902 that's a great idea, I think text would be much better than the way React Table displays there's no data. Once we do this, I think we can either change `minRows` to 1 or remove the properly entirely. It has to be set to at least 3 right now or the message that shows up when there's no data looks weird, but the flip side of that, is tables with just 1 or 2 records look odd.

**Comment by dzimmerman902** [comment]
@seankwilliams I definitely agree that having a table with min rows of 3 is good even with data so
