### ISSUE TITLE
Rich Text Area Component

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#417]
## Description of Issue

We need an component similar to the `Input` and `Textarea` components, but one that provides a rich text editing area. The field should support the following functionality:
- h2 tag
- h3 tag
- hyperlinks
- bold
- italicize

## Possible Solution and/or Approach

Tiny MCE is a common JavaScript plugin for this, though it may be overkill for this.

**Comment by kmid5280** [comment]
@seankwilliams I might give this one a shot. Do you think Draftjs would work okay for this?

**Comment by seankwilliams** [comment]
@kmid5280 that would be great! Draftjs looks good at first glance. I haven't dug deep but I say let's give it a shot and we'll find out if we come across any issues with it.

**Comment by kmid5280** [comment]
@seankwilliams So far what I have is a working textarea with some functionality. You can make the text bold or italic by clicking on the component and using the keyboard commands ctrl-b and ctrl-i. However it still needs a toolbar and some style.

**Comment by seankwilliams** [comment]
@kmid5280 great, I'm looking forward to seeing the finished product!

**Comment by kmid5280** [comment]
So far I have a working toolbar that will change the text to bold, underline, and choose headers. Running into a snag though in that this particular plugin doesn't include hyperlinks. There are codeblock buttons but I'm not sure if that will have the same effect. Think there may be a way to custom add a hyperlink button in there, or perhaps we should use a different plugin altogether?

**Comment by seankwilliams** [comment]
@kmid5280 Nice job on the working toolbar! That's too bad about the hyperlink button: adding hyperlinks is a really important functionality since people will want to link from their shows descriptions to event links, sites of underwriters, and more information on announcements during the program - among other things. The code block button is unfortunately too much to ask of the DJs since we won't expect them to have any HTML familiarity. So, there's two options: either build a hyperlink button for Draft JS or switch to a different plugin. Which do you think is best?

**Comment by dzimmerman902** [comment]
@seankwilliams @kmid5280 

https://github.com/zenoamaro/react-quill

**Comment by kmid5280** [comment]
Thanks for the feedback. Just so I'm clear, do you need an actual clickable button in the toolbar, or are you looking more for just the ability for the component to automatically turn a URL (say one that is copy and pasted into the component) into a clickable hyperlink once it is inserted?

**Comment by seankwilliams** [comment]
@kmid5280 an actual clickable button, so that users can make the text of the link different than the URL.

**Comment by kmid5280** [comment]
@seankwilliams I currently have a mostly working toolbar with the buttons requested. It has bold, underline, headers, link, and code removal button. If you import this in the library search page you can try it out. I notice though that the underline works, but the bold and italic don't, and I'm wondering if it's just defaulting to a font that doesn't support those. You can use keyboard shortcuts too, i.e. ctrl+u for underline, though ctrl+b and ctrl+i aren't appearing to do anything.

**Comment by seankwilliams** [comment]
@kmid5280 that's looking great so far! As far as bolding and underlining not appearing: inspect the element's CSS on the bolded/italic text. I think the plugin is expecting `b` to be bold by default and `em` to be italic, and that's not the case in our CSS so you'll want to add a rule that targets those elements when they are inside the `RichTextArea`

**Comment by kmid5280** [comment]
@seankwilliams Okay, see how that looks. If this looks okay I think the only thing left will be to style the component itself. Will also need to make sure that the formatting of the styled text actually gets saved when submitted.

**Comment by seankwilliams** [comment]
@kmid5280 looking good so far, looking forward to seeing the rest once it's done!

**Comment by kmid5280** [comment]
@seankwilliams Do you have any suggestions as to how to style this thing? Most of the styling is imported via stylesheets that come with the distribution.

**Comment by kmid5280** [comment]
@seankwilliams It looks like I'm able to style the component now. I can override the values in the distribution CSS by specifying my own values in the sass file. What style suggestions do you have, and is there anything else I should look into on this component?

**Comment by seankwilliams** [comment]
@kmid5280 Sorry for the delay here, I was out of town over the weekend. Please do a `git pull` when you get a chance: I've synched your branch with development. I've been testing on the Add Artist page, which you can test by adding this after line 28 of `client\src\components\FormArtistAdd\FormArtistAdd.js`:

```
<Field
          component={RichTextArea}
          label="Test"
          name="test"
          autoFocus
          validate={requiredValidate}
        />
```

Here's what I would suggest:

- [ ] Rename "Heading 2" to "Large Heading" and "Heading 3" to "Small Heading". Most people using this won't know what an `h2` or `h3` is so that naming will make more sense to them. Also, I don't want them asking why they can't choose `h1` (the reason is that `h1` has a particular use for search engine optimization and should only be set once per page)
- [ ] Display-wise, my only comment is to display the toolbar below the textarea. having it above the textarea messes up with the way the label animates to the top. When you do this, I would keep the toolbar inside the blue outline, then remove the left/right/bottom gray borders from the toolbar so there is only a gray border on the top of the toolbar. This should make it look like the toolbar is seamlessly fitting in the bottom of the textarea. And hopefully, by putting the toolbar below the textarea, we can prevent the issue where the buttons are wrapping and keep the toolbar just in one line:

![add-artist-example](https://user-images.githubusercontent.com/151931/57261258-55ac4e80-7024-11e9-924c-b8d142976831.PNG)

**Comment by kmid5280** [comment]
@seankwilliams Ok, getting there, but I'm running into a few snags.

-Currently you have a parent editor-container div, which contains the text editor and toolbar. I want the toolbar to occupy a fixed amount of space, while the text editor stretches to fill the rest of the height of the parent div. I have tried several approaches and it doesn't want to do this. Currently I have the height set to a fixed height but I realize that's not ideal.

-Sometimes if no text is entered the 'required' label can pop up and interfere with the style. It might push the toolbar down and outside of its parent container.

**Comment by seankwilliams** [comment]
@kmid5280 Here's how I'd suggest settings this up:

1. First, to fix the problem with the "Required" label, you'll want to use `position:absolute` on the `.richtextarea__error` class. Take a look at the styles for the `.input__error` class. The styles should be pretty similar to that.
2. Then, you're going to want to position the toolbar via absolute positioning. If you give it a value of `position:absolute` along with `left:0px; right:0px; bottom:0px`, you'll find that it sticks to the bottom of the textarea. 
3. Then, you'll run into a problem where, since the toolbar is absolutely positioned, it won't count towards the height of the parent element. So, we'll need to make up for this by adding more space to another element. So, try to add padding-bottom or margin-bottom to the `.richtextarea` class to give the container the space it needs for the toolbar.

**Comment by seankwilliams** [comment]
@kmid5280 And also, where did you set the fixed height? I glanced through but didn't see where that was.

**Comment by kmid5280** [comment]
@seankwilliams I was able to position the toolbar at the bottom and stretch it appropriately. Regarding the fixed height, sorry for the confusion. What I meant was the height value in ql-editor is currently set at 90px - in other words it is given a set value instead of being automatically sized to fit, if that makes sense.

**Comment by seankwilliams** [comment]
@kmid5280 Great! And thanks for the clarification on the fixed height. You know, I'm not sure the fixed height is an issue as long as there's a way to set some different classes to do different heights (one might make it 180px, one might keep it 90px, etc.) But, if you want to avoid the fixed height, I'd try seeing if you can use `display:grid` on the parent container to get `.ql-editor` to stretch to the height of its parent. I haven't tried that to see if it will work though.
