### ISSUE TITLE
User filter is case sensitive - usability issue

### ISSUE THREAD

**Issue by jberns** [codefordenver/Comrad#428]
## Description of Issue

When using user filter (and other filters), unless the filter string matches by case it won't return any results.

For example: 'all' returns no results, the user search is expecting 'All'

## Possible Solution and/or Approach

When doing filters on the backend, we can `toLowerCase()` the filter string against lowers of the possible enumerations to determine which filter to use.

**Comment by dzimmerman902** [comment]
@jberns I agree, it's something I've been going back and forth on. I kept some of the database values with capital first letters because it was easier to incorporate on the front-end (without having to create a function that will capitalize the letter). But I can definitely see why this will cause issues in the future. 

I'm going to do some research and see how some companies model their databases and how they handle this kind of stuff.

**Comment by jberns** [comment]
There is no way to keep the database entry with the case but then do a non-case sensitive filter?

**Comment by dzimmerman902** [comment]
This is new for me, not sure how to approach this. @seankwilliams, do you have any suggestions on how data should be saved and queried?

**Comment by jberns** [comment]
Is there much benefit to pre-filtering the users in mongo?  Can we return all the users then just filter in javascript after, something like (all sudo code):

```
users = (all users from mongodb)
filterValue = (value from api request)
const filteredUsers = users.filter(user => user.status.toLowerCase() === filterValue.toLowerCase());
```

**Comment by dzimmerman902** [comment]
I think I have a solution, I'll commit it sometime tomorrow

**Comment by seankwilliams** [comment]
@dzimmerman902 Using `toLowerCase()` is a great solution (like you did), and sometimes database engines have a way to search in a case-insensitive fashion (I'm not sure what Mongo provides here).

**Comment by dzimmerman902** [comment]
@seankwilliams I've been using RegEx with mongoose and they compliment each other very well. It helps with a lot of edge cases instead of having to tweak the request body so much.
