### ISSUE TITLE
Update Traffic Icon

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#430]
## Description of Issue

The traffic Icon on the sidebar looks very similar to the calendar, might cause some confusion. I was thinking a picture of a little car!

## Possible Solution and/or Approach

<img width="77" alt="Screen Shot 2019-04-27 at 5 56 24 PM" src="https://user-images.githubusercontent.com/18602363/56856339-d200ac80-6915-11e9-9385-4d4bc7879185.png">

## Additional Comments

N/A

**Comment by seankwilliams** [comment]
Closing this - @dzimmerman902 has got this fixed!
