### ISSUE TITLE
Show Calendar - DST causing offset of 1 day on calendar when processing dates

### ISSUE THREAD

**Issue by jberns** [codefordenver/Comrad#434]
## Description of Issue

When viewing the start and end of DST, there is an offset of 1 day because of the time shift during the post processing.

## Possible Solution and/or Approach
Can look for DST and then if true, you can offset all the shows forward one day.  Need to do some testing on how valid this is, and if there are any other edge cases on the calendar events. that happen around the DST shift.

**Comment by seankwilliams** [comment]
This is done
