### ISSUE TITLE
Show Calendar - Determine if date includes midnight

### ISSUE THREAD

**Issue by jberns** [codefordenver/Comrad#436]
## Description of Issue

If the date includes midnight, the show will be automatically placed in the all day field.

## Possible Solution and/or Approach

Split show in two if it crosses midnight after localized.
Show 1 = x -> 11:59:59
Show 2 = 00:00:01 -> y

All other attributes should be the same when updating.
## Additional Comments

_Comments Go Here_

**Comment by seankwilliams** [comment]
Marking this as v2 - KGNU does not have events that cross midnight, but other stations will so we will have to account for this.
