### ISSUE TITLE
Error when displaying Alert component

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#474]
## Description of Issue

Steps to replicate:
1. Go to http://localhost:3000/library/artist/5be9d30e294ca24bac27eab2
2. Change the artist name to "The Beatles", which will return an error since it has the same name as another artist in the database.
3. You'll get the following error:

![Screen Shot 2019-06-08 at 12 35 07 PM](https://user-images.githubusercontent.com/151931/59151048-f6a67480-89e9-11e9-8593-6ff805660506.png)

**Comment by seankwilliams** [comment]
@dzimmerman902 would you be able to take a look at this or give me a walkthrough on how alerts should be working? I'd like to start implementing alerts in a few other places but I don't want to be copying over the wrong implementation.

**Comment by dzimmerman902** [comment]
@seankwilliams Remind me today at CFD and I'll go over it.
