### ISSUE TITLE
Keyword search of library

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#50]
Search for library of tracks via some API

**Comment by seankwilliams** [comment]
We need an API endpoint that returns matching tracks based on a keyword search. The keyword search should take a single search term and find matching tracks based on:

- Track artist
- Track title
- Album artist
- Album label
- Album title
- Genre name

The API endpoint should return a maximum of 30 results, ordered by relevancy so the most relevant tracks to the search terms are first.

In SQL, this would be done using what is called a full-text search. I am not sure what the Mongo equivalent of this is.

**Comment by msiadak** [comment]
Do we want to paginate the results beyond 30 or just discard them for now?

**Comment by seankwilliams** [comment]
@msiadak just discard them. If a user doesn't see what they want immediately, they will just try another search.

**Comment by msiadak** [comment]
Closed by #211
