### ISSUE TITLE
Add Genre to music library

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#502]
Albums will need to have genres for use in reporting. For example, music directors will want to pull the most popular tracks played in a given month for a particular genre. Add a Genre dropdown to the Edit Album and Add Album pages.

- [ ] Set up an API endpoint to get all genres from the database (they are in the `genre` model)
- [ ] Set up a new set of Redux action, reducer and type for genres. Model this off of the folder and file structure that the `album` redux function uses.
- [ ] Set up a Redux action to retrieve the genres from the new API endpoint and place the  genre list in the Redux store
- [ ] Modify the Edit Album and View Album page so that, if the genre list is not loaded into the Redux store on page load, the page calls the Redux action to retrieve genres
- [ ] Add a dropdown to the Edit Album and View Album pages with the options for genre. This field should be optional.

**Comment by kmid5280** [comment]
@seankwilliams I'm making some good progress on this. The API works and calling it will return the list of genres. I have so far implemented this on the album view page.

Two issues. One, I notice that when I put the conditional in ComponentDidMount to call the action, it fires off several times. You can see that in the console.log I added in the component.

Two, it is currently returning a list of objects. Any suggestions as to how I can simply get the list of genre names from that to populate in the dropdown menu?

**Comment by seankwilliams** [comment]
@kmid5280 The progress on this is looking great! In the latest code, the console.log is actually in the `render` function: which would fire multiple times, because it's going to fire any time the component's properties change. The action seems to be firing only once: at least, I'm only seeing one API call happening when I inspect the page with dev tools.

To change the API to return something different than a list of objects, you'll want to modify the code in `server/v1/controllers/genres/findAll.js `. Right now, it's just converting the response from `.find()` to JSON and outputting that. So, you can approach one of two ways to change that to an array: see if there's a way with Mongoose to only return the Genre names as an array (there might be a way to do that with projections but I'm not sure). Or, manipulate the response you get from `.find()` to change it so it's just an array. I think either solution is a good option. I'm not sure how to do that in Mongoose, but if you find out, it would be useful to know!

**Comment by kmid5280** [comment]
@seankwilliams How about something like this? Although, this solution is still returning an object. {0: 'rock', 1: 'funk'} and so on.

`function findAll(req, res) {
  return db.Genre.find()
  .then(genres => {
    let array = []
    for (i=0; i<genres.length; i++) {
      array.push(genres[i].name)
    }
    res.json(array)
  });
}`

**Comment by seankwilliams** [comment]
@kmid5280 that works, and it actually is returning an array! It can just look like an object when you're inspecting in browser dev tools sometimes (it's presented in a confusing way). Here's the raw result from that API call:

![genre-results](https://user-images.githubusercontent.com/151931/61807739-5a98c700-adf7-11e9-9f20-e98ced8c259e.PNG)

**Comment by kmid5280** [comment]
@seankwilliams It's actually still returning an object. I had to convert the object to an array with some javascript in the edit album form itself. The whole thing looks clunky and probably isn't optimal, but I'm not sure how else to do it. At any rate though I do have an array of genres in the form ready to be implemented.

What do you suggest I use for the dropdown menu to display the list of genres?

**Comment by seankwilliams** [comment]
@kmid5280 okay, sounds good. I would use the `Select` component for that, which renders a `select` element and has been set up to work with Redux Form. If you need a reference for where that's used, it's only been used once and I believe that's on the Edit Album form - a `Select` is rendered inside the `CustomFieldsEdit` component.
