### ISSUE TITLE
Music Library: Add Release Date to albums

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#503]
Let's add a new Release Date property to albums. This will be a date value (month, date, year). Here are the steps to set this up:

- [x] Add a new `release_date` property to the library model
- [x] On the Add & Edit Album pages, add a field for the release date using the `DatePicker__React` component from `components/DatePicker`
- [x] On Show Builder, when you click a track in the scratchpad or saved items to see more information, display "Album Release Date: [the release date value]" in addition to the information that is already displayed
- [x] On Show Builder, when you search for a track that does not exist and use the "Add New Track" feature, ensure that the album release date is displayed in the form to add a new album. This uses the `FormAlbumAdd` component, so the field should appear here after adding it to the Add Album page, but please ensure that it works properly.

**Comment by kmid5280** [comment]
@seankwilliams I see that in the library model, the different properties are organized based on what will use them, i.e. albums, artists, tracks. Is the release date property going to be used by all three, or only by certain things?

**Comment by seankwilliams** [comment]
@kmid5280 Albums only!

**Comment by kmid5280** [comment]
@seankwilliams Okay. On step 3, are you talking about adding the release date info within the expandable section of the show builder item?

**Comment by seankwilliams** [comment]
@kmid5280 Yes, that's correct

**Comment by kmid5280** [comment]
@seankwilliams So far I have gotten to the point where I can create a new album, specify the release date when adding it, and have the release date show up in the expandable section. If you want to test it, you might have to create a new album, as I am not sure that any of the existing ones will have the new `release_date` property.

Also in the last commit, I corrected an issue with the copy icon we implemented, changing `class` to `className`. Rookie mistake I guess.

How does it look so far? I don't think we're finished yet, but is it on the right track?

**Comment by seankwilliams** [comment]
@kmid5280 This is looking great so far!

Can you change the spacing below the Release Date field so that there's the same padding between "Release Date" and "Local Artist" as there is between "Artist" and "Compilation"?

![image](https://user-images.githubusercontent.com/151931/121247019-5f3dbb80-c867-11eb-93df-e6c6027721ff.png)

Also, when I use the artist autocomplete, the "Release Date" field sits on top of the autocomplete. Can you take a look at that?

![image](https://user-images.githubusercontent.com/151931/121247313-b774bd80-c867-11eb-9a53-12ac2a52df20.png)

And, on Show Builder, please make the "Release Date" text in bold:
![image](https://user-images.githubusercontent.com/151931/121247948-6e713900-c868-11eb-9c5c-340ee2033b59.png)

I believe the Release Date still needs to be added to the Edit Album form. Once the field is created on that form, you should be able to set the release date for existing albums.

**Comment by kmid5280** [comment]
@seankwilliams The latest commit should fix the above issue.

I am trying now to implement the field in the Edit Album form as well. I have succeeded so far in adding the `release_date` property to the initialValues. The issue now is getting the new field that uses the Datepicker component to display the album's current release date, if there is one. As you can see I added the new input field, but commented out the `name` property, as including it throws an error within the Datepicker component (which I think has something to do with the way it is handling the date formatting?) What do I need to set that to to ensure the current release date displays correctly?

**Comment by seankwilliams** [comment]
@kmid5280 I'm not sure after looking at it for a bit. What steps have you tried while troubleshooting the error message? This error message makes it sound like the issue because the data type that gets passed into the datepicker component ultimately ends up being a string rather than a date object:

![image](https://user-images.githubusercontent.com/151931/121971070-80a61800-cd3d-11eb-9203-252e42ee76ce.png)

**Comment by kmid5280** [comment]
When adding the `release_date` property to `initialValues` on line 129, I tried using moment.js to format it. For example:

`release_date: release_date ? moment(release_date).format('YYYY MM DD') : null,` and
`release_date: release_date ? moment(release_date).toDate() : null,`

This was done with the idea that there is a particular format it is expecting the date in, but if this is the case I haven't stumbled on the right format.

I see that FormTraffic.js appears to use a function to update the date and time in Datepicker called `updatedDateTime`. Do you suppose a similar approach may be needed here?

**Comment by seankwilliams** [comment]
Thank you @kmid5280 , those details are helpful!

I spent some time with it and I found out the issue is in how `DatePicker__React` is being imported. We have two different datepickers in the project, and the wrong one is being brought into the album edit form. Right now, `FormAlbumEdit` uses this import:

`import DatePicker__React from '../../DatePicker';`

That's importing the default export from this file:

`client/src/components/DatePicker/index.js`

Which is actually a datepicker component from AirBnb. That is different than what's in use on `FormTraffic`. To fix, you'll have to change the import to be like this (with the curly braces):

`import { DatePicker__React } from '../../DatePicker';`

Can you give that a try and see if you can get it working?

**Comment by kmid5280** [comment]
@seankwilliams Looks like that worked. I pushed the change. Now the Datepicker on the album edit page will display the existing release date, the user can change the date, submit, and it will save the changes.

I notice though that the Datepicker is also showing the time. I can remove that so it only displays the date, but if you change the date, the dropdown also includes the time. I don't see how the time is relevant for a release date. We could try to find some way to disable the time selection, though I would need to know where the docs are for this specific Datepicker component and see if there is a way to do that.

**Comment by seankwilliams** [comment]
@kmid5280 I would compare your usage of the datepicker to the one that's in use in the RepeatDropdown component at `client/src/components/RepeatDropdown/RepeatDropdown.js` (the one that's used on the traffic form). I believe the datepicker there does not have times

**Comment by kmid5280** [comment]
@seankwilliams Okay, I found the issue. There are different variants of Datepickers I can use, and I was able to access the one I wanted by removing the `type='time'` attribute from the component in the Edit Album page.

I also went into the model we created for the new release date property and set the default value to `null`, because it was autopopulating today's date in the component whenever the album didn't already have a release date. This should clear up that issue.

Let me know how this looks so far and if any other changes are needed.

**Comment by seankwilliams** [comment]
Thanks @kmid5280 ! I am getting this error when visiting some pages in Show Builder. I believe it's happening the first time you access Show Builder for a particular show instance. Can you take a look?

![image](https://user-images.githubusercontent.com/151931/122251593-426d3d80-ce90-11eb-9737-3bec33374bd7.png)

**Comment by kmid5280** [comment]
@seankwilliams I think I was able to fix this. Try it now.

**Comment by seankwilliams** [comment]
That worked, thanks @kmid5280 ! Last thing, I think. The Add form still has issues where the datepicker isn't sitting on top of other fields:

![image](https://user-images.githubusercontent.com/151931/123001037-e9ad1180-d375-11eb-9161-b899ac562ad5.png)

Can you fix this? Seems we could resolve by switching the datepicker on the Add page to use the same component as the Edit page.

**Comment by kmid5280** [comment]
@seankwilliams Okay, that should be fixed. Since that should wrap it up, I made a PR, but let me know if there are still other issues.

**Comment by seankwilliams** [comment]
Beautiful. Great work, @kmid5280 ! I'll merge that in now.
