### ISSUE TITLE
Music Library: track number and disk number should not be required

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#505]
Modify the model and forms for tracks so that track_number and disk_number are not required.

**Comment by kmid5280** [comment]
@seankwilliams Did someone already get to this one? I'm not seeing that the disk and track numbers are required per the models or the add track form. I do see a validator in use in the edit track form though.

**Comment by seankwilliams** [comment]
@kmid5280 I might have gotten the model piece. In that case, all we need for this one is to remove the validator from the form.
