### ISSUE TITLE
Show Calendar - Series repeat edit

### ISSUE THREAD

**Issue by jberns** [codefordenver/Comrad#561]
## Description of Issue
Currently the repeat of a series cannot be edited as there is no way to directly match the initially selected value of the new series with returned value of a created series.

- [ ] Frontend - Determine a way to show the currently selected repeat rules
- [ ] Backend - Make sure edited repeat rules are properly assigned on the shows/series/update endpoint controller

## Possible Solution and/or Approach

_Insert Possible Solution/Approach Here_

## Additional Comments

_Comments Go Here_

**Comment by seankwilliams** [comment]
@jberns Do you happen to remember why the Repeat Start Date is set to `disabled` so the user can't edit it? No worries if you don't, just curious.
