### ISSUE TITLE
Tab Should Hightlight Next Button

### ISSUE THREAD

**Issue by dzimmerman902** [codefordenver/Comrad#569]
## Description of Issue

Edit User Name Mode. When user hits tab, it should not automatically submit form, it should hight the checkmark and x for those who like to use the keyboard.

## Possible Solution and/or Approach

No Idea

## Additional Comments

![Screen Shot 2019-08-19 at 5 17 04 PM](https://user-images.githubusercontent.com/18602363/63305777-72078a80-c2a5-11e9-91e8-666b716cd249.png)

**Comment by kmid5280** [comment]
@seankwilliams I pushed latest changes to branch 569-tabkey describing steps taken to try to resolve the issue. I attempted to implement event listeners to watch for keystrokes, set up refs, and function called handleBlur that would handle the input's onBlur attribute. The idea is that the handleBlur function would use a ref to call the form onSubmit attribute if it detects that any key was pressed other than the tab key. However I was not able to get the handleBlur function to properly call the form onSubmit. Using onKeyDown attribute had the effect of causing form to submit on any keystroke, even when only implemented in onBlur attribute.
