### ISSUE TITLE
Reporting request: giveaway export

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#581]
Request from KGNU: Ability to export all ticket giveaway winners from the database. Implement as all ticket winners over a specific date range.

*REQUIREMENTS*
Add a page to the Reporting section called "Giveaway Winners". This should only be accessible to users with permissions to read traffic events.

Have two fields on the page in a form:
- Date range from (defaults to the earliest giveaway instance in the traffic database)
- Date range to (defaults to today)
Both fields should be required.
The form should also have an "EXPORT" button

Clicking Export should download a *.csv file with the following information for each ticket giveaway (all but the first are properties of `giveaway_details` in the `traffic` model). The rows should be ordered by the giveaway date/time, and should be filtered to traffic instances that occurred within the provided date range:
- Giveaway date/time (the traffic instance's start date/time)
- Event Name
- Event Date
- Winner Name
- Winner Email
- Winner Phone
- Winner Adress

**Comment by dzimmerman902** [comment]
@seankwilliams Which api and what properties should we be hitting up?

Do they want it exported as an excel/csv file?

**Comment by seankwilliams** [comment]
@dzimmerman902 Description updated with more details!
