### ISSUE TITLE
Show Builder: Most traffic events are not populating correctly from the database

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#587]
## Description of Issue

Go to http://localhost:3000/show-builder/show?startTime=2019-03-13T15:30:00Z&endTime=2019-03-13T18:06:00Z. There are a bunch of traffic events that should be populating, but are not:

![missing-traffic-events](https://user-images.githubusercontent.com/151931/64755091-2b453300-d4e7-11e9-86f3-efa9a48cbbde.PNG)

**Comment by seankwilliams** [comment]
The problem here is that RRule is not adjusting for daylight savings time. If a traffic event is set up to repeat at 10am weekdays:

```
 { repeat_rule:
    { byweekday: [ 'MO', 'TU', 'WE', 'TH', 'FR' ],
      repeat_start_date: 2011-04-11T16:00:00.000Z,
      frequency: 2,
      repeat_end_date: 9999-01-01T07:00:00.000Z },
   traffic_details:
    { type: 'Feature',
      title: 'Fundraising & Outreach',
      description: '',
      producer: 'Current DJ',
      custom:
       { old_comrad_event_id: '138',
         old_comrad_scheduled_event_ids: [Array] } },
   status: 'active',
   exclude_dates: [],
   _id: 5d79923cedcc2652309fece0,
   start_time_utc: 2011-04-11T16:00:00.000Z,
   end_time_utc: 2011-04-11T16:01:00.000Z,
   is_recurring: true,
   created_at: 2019-09-12T00:33:00.973Z,
   updated_at: 2019-09-12T00:33:00.973Z,
   __v: 0 }
```

Then, it will repeat at 10am within Daylight Savings Time, but 9am when in standard time.

**Comment by seankwilliams** [comment]
@jberns I'm troubleshooting a daylight savings time issue and wondering if you've got any insight on this. Do you know what causes the daylight savings adjustment in the show find endpoint so that Restless Mornings in http://localhost:3000/v1/events/shows?startDate=%222019-12-11T07:00:00.000Z%22&endDate=%222019-12-12T07:00:00.000Z%22 happens at 10:00 UTC but Restless Mornings in http://localhost:3000/v1/events/shows?startDate=%222019-10-16T06:00:00.000Z%22&endDate=%222019-10-17T06:00:00.000Z%22 happens at 9:00 UTC?

**Comment by jberns** [comment]
So it looks like the date time is as follows:
1. Database > UTC w/o any time zone information
2. After reading from the database when object is on the server Before RRule > Localized time including time zone information (Updated my timezone to pacific to check)
<img width="604" alt="Screen Shot 2019-09-14 at 9 29 22 AM" src="https://user-images.githubusercontent.com/519070/64911219-9a7f7a80-d6d3-11e9-8597-216ddcd80841.png">
3.  After running a date range through the repeat rule > Localized date to server time including DST correction if applicable
<img width="1392" alt="Screen Shot 2019-09-14 at 9 52 44 AM" src="https://user-images.githubusercontent.com/519070/64911384-fe0aa780-d6d5-11e9-82e0-a3f6870dd7ad.png">

Looking at the current traffic events the way they are shown in the database, it looks like they were 'pre' localized by an hour into the database when they were put in as UTC and then our implementation is localizing it again which is why it is off by an hour.  If you look at the screenshot the time changes by an hour, but the timezone also changes by an hour so in terms of UTC it will be the exact same time with a timezone offset of 00:00.

**Comment by seankwilliams** [comment]
@jberns Thanks for this info! I'm continuing to look into this to see what we can do about this. The rrule library supports adding a `tzid` parameter for an `RRule`, and that makes it so DST is handled properly. But, it also has awful performance so I'm going to think about it a bit and see what the best route will be to fix this. I'll keep you posted!

**Comment by jberns** [comment]
I don't think the tzid will be a direct fix, and if you have to update the tzid on everything you are probably better off just fixing the UTC time/offest on the ones that are incorrect.

If the time is correct coming into the frontend, it should be possible to localize between any two timezones regardless with what time is output from the server.

**Comment by seankwilliams** [comment]
@jberns Gotcha, so do you think it's an issue with the underlying data or it's in the processing? Here's the data I'm testing with. I'm not sure it's an issue with the underlying data, I think there's something in the processing, and if providing `tzid` isn't the right fix, it does at least fix the issue I'm seeing.

Here's the sample data I'm testing with, in the dev database, and the results I'm getting

Traffic ID 5d79923cedcc2652309fece0
Event should repeat at 10am every weekday

Testing the results from these two queries:
9:30am-12:06am MST query: http://localhost:5000/v1/events/traffic?startDate=%222019-01-03T16:30:00Z%22&endDate=%222019-01-03T19:06:00Z%22
8:30am-11:06am MST query: http://localhost:5000/v1/events/traffic?startDate=%222019-01-03T15:30:00Z%22&endDate=%222019-01-03T18:06:00Z%22

I'd expect both of these queries to return the event, and have it at 10am MST that day.

What was in the database - this was in the correct time, 16:00 UTC = 10am MDT
```
"repeat_rule.repeat_start_date":"2011-04-11T16:00:00.000Z",
"start_time_utc": "2011-04-11T16:00:00.000Z",
"end_time_utc": "2011-04-11T1601:00.000Z",
```
Results:
9:30am query: did not contain event (incorrect)
8:30 am query: contained event
Repeating event's start time: `2019-01-03T16:00:00Z` (incorrect, should be 17:00)

```
"repeat_rule.repeat_start_date":"2011-04-11T17:00:00.000Z",
"start_time_utc": "2011-04-11T17:00:00.000Z",
"end_time_utc": "2011-04-11T1701:00.000Z",
```
Results:
9:30am query: contained event
8:30 am query: contained event
Repeating event's start time: `"2019-01-03T17:00:00Z` (correct, should be 17:00)

BUT - with this, a query at http://localhost:5000/v1/events/traffic?startDate="2019-07-03T15:30:00Z"&endDate="2019-07-03T18:06:00Z" still returns 17:00 - and it should be 16:00 since 7/3/19 is in MDT, not MST.

```
"repeat_rule.repeat_start_date":"2011-04-11T15:00:00.000Z",
"start_time_utc": "2011-04-11T15:00:00.000Z",
"end_time_utc": "2011-04-11T15:01:00.000Z",
```
Results:
9:30am query: did not contain event (incorrect) 
8:30 am query: contained event
Repeating event's start time: `"2019-01-03T16:00:00Z` (incorrect, should be 17:00)

```
"repeat_rule.repeat_start_date":"2011-04-11T14:00:00.000Z",
"start_time_utc": "2011-04-11T14:00:00.000Z",
"end_time_utc": "2011-04-11T14:01:00.000Z",
```
Results:
9:30am query: did not contain event (incorrect) 
8:30 am query: contained event
Repeating event's start time: `"2019-01-03T15:00:00Z` (incorrect, should be 17:00)


With tzid provided, this data is returning the expected results for the 1/3/19 date and the 7/3/19 query:
```
"repeat_rule.repeat_start_date":"2011-04-11T16:00:00.000Z",
"start_time_utc": "2011-04-11T16:00:00.000Z",
"end_time_utc": "2011-04-11T1601:00.000Z",
```

**Comment by seankwilliams** [comment]
I think the solution here will be to provide `tzid`, as the station's time zone, so that all events are properly adjusted for Daylight Savings Time. However, the rrule library had some serious performance issues when using `between` in conjunction with an rrule that had `tzid`. I've forked rrule and fixed the performance issues at https://github.com/seankwilliams/rrule. I'll prepare a pull request into the main branch of the repo eventually, but in the meantime, I'm going to update Comrad to pull from seankwilliams/rrule.

Here's data on the optimizations:
Execution time for `rrule.between`, on Dashboard page load:
- rrule.between runs 88 times between the three API requests on Dashboard

Without tzid in rrule, using out-of-the-box rrule: 
690ms of execution time (7.8ms per execution of `between`)

With tzid in rrule, using out-ofthe-box rrule:
17564ms of execution time (199.6ms per execution of `between`)

With tzid in rrule, using seankwilliams/rrule, after https://github.com/seankwilliams/rrule/commit/9b99658d23e45ca762df0354694e13deeef70165:
9610ms of execution time (109.2ms per execution of `between`)

With tzid in rrule, using seankwilliams/rrule, after https://github.com/seankwilliams/rrule/commit/e686263f477b36bf9646965f977c910ffe9c5a72:
727ms of execution time (8.3ms per execution of `between`
