### ISSUE TITLE
What Makes Your Solution Different?

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/Comrad#6]
### What is your Unique Value Proposition?

Fill in Box 3, the "Unique Value Proposition."

![leancanvas-box3](https://cloud.githubusercontent.com/assets/100216/12663596/cd50f72e-c5e6-11e5-8d40-4daeaf0365a3.png)

#### What is a UVP? 
Your unique value proposition is the promise you're making to your customer that's compelling enough for them to jump on board.

#### Writing a UVP
Here are two suggested formats: 

1) Ask yourself: "If I solve *the problem* `[by doing this]` for *my customer*, is that compelling?" 

When you can substitute `[by doing this]` with something compelling, that's the Unique Value Proposition you're proposing.

2) Complete the statement: "I can promise [the customer in Box 1] who faces [the problem in Box 2] that I can give them [unique value proposition in Box 3]."

Lastly, don't forget to fill out the `High Level Concept`! This serves as a clear way to describe who you are. For Uber, this would be "Order a taxi with your phone." It can also be an 'x for y' concept like "Instagram for Pet Lovers."

**Comment by dzimmerman902** [comment]
### Unique Value Proposition

- We can promise members in the community radio segment a lower cost alternative for producing radio programs that are within the compliance of the FCC.
- We promise to make our interface user friendly and give them the ability to add modules to enhance functionality.
- Lastly, we promise to give our consumers the ability to apply our technology to their native languages, especially Hispanic speaking radio stations.

### High-Level Concept

Radio software for small radio communities
