### ISSUE TITLE
Show Builder: Allow copying/pasting text in the expanded traffic descriptions

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#655]
## Description of Issue

Currently, you can't highlight text in the description text that appears in Show Builder when you expand it. You should be able to.

**Comment by kmid5280** [comment]
@seankwilliams I played with this and was able to disable the dragging when clicking on the expanded section of the item. However this does not translate to being able to select the text. I'm not sure to what extent react-dnd supports this, or whether it allows for text selection inside a draggable item.

A few StackOverflow questions deal with this such as [this one](https://stackoverflow.com/questions/52519644/cant-select-text-within-draggable).

I suspect we will either have to find a way to implement text selection within the react-dnd library, or find some way to separate that expanded child div from the rest of the draggable item. If we did the latter, I would wonder if the child div ends up getting dragged when the parent div is dragged.

**Comment by seankwilliams** [comment]
@kmid5280 Got it! I assume if we turn off react-dnd completely, text selection will work, right? If so, I'm surprised that it didn't work when you disabled the dragging on the expanded section. I wonder if react-dnd is hijacking the mousedown event on that section in some way. If that's the case, we might be able to stop the mousedown event from ever getting to react-dnd if you use event.stopPropagation() on the mousedown event for the expanded section.

**Comment by kmid5280** [comment]
@seankwilliams I attempted adding the following property to the expanded section:

`onMouseDown={e => {
            e.preventDefault();
            e.stopPropagation();
          }}`

This didn't work though, and I suspect it may have something to do with the way React handles bubbling events. A StackOverflow discussion about it [here](https://stackoverflow.com/questions/24415631/reactjs-syntheticevent-stoppropagation-only-works-with-react-events). The discussion concerns React and jQuery but the same principle may apply in this case? I'm just speculating.

**Comment by seankwilliams** [comment]
@kmid5280 Have you tried anything with the `e.nativeEvent.stopImmediatePropagation()` function mentioned in that StackOverflow article? That might be the right command, but to get it to work, you may have to go through the code of the ReactDnd library to figure out the exact sequence of events and what's preventing this to fire.

This issue has been logged on ReactDnd's GitHub: https://github.com/react-dnd/react-dnd/issues/2690

https://github.com/react-dnd/react-dnd/issues/358 also mentions a similar issue, and one thing that might work is the comment about using a property like `isEditing`. Rather than an `isEditing` property, we could do something like `isMouseOverExpandedText`, and set that to true when the mouse hovers over the expanded text, and set it to false when the mouse leaves that text. That way, ReactDnd would basically be off when you're hovering over that text. If that solution works, we'll want to be sure to test it well because it's unconventional so it could cause some unintended issues on the page.

**Comment by kmid5280** [comment]
@seankwilliams Some of these fixes seem a little elaborate, and it sounds like they have a risk of unintended side effects.

What if instead of trying to enable dragging over the text, we added a "Copy" icon next to the text that would copy the text to the clipboard when clicked? It might be a little more straightforward to implement.

**Comment by seankwilliams** [comment]
@kmid5280 Good thinking, let's add that "Copy" icon!

**Comment by kmid5280** [comment]
@seankwilliams I played with it and so far, I have an icon and a method that can copy the text to a clipboard.

What I need now is a way to target the text of the individual scratchpad item. I can access the text of all of the items cumulatively via the `children` property, but how can I be more specific and target the exact text I need from this?

**Comment by seankwilliams** [comment]
@kmid5280 Are you trying to get the text in a JavaScript variable, or target the element that contains the text? If it's a JavaScript variable, you'll want to look at whatever makes up the `children` property and try to access those values. If you're trying to access HTML elements, then I'd see if React's refs can do that.

**Comment by kmid5280** [comment]
@seankwilliams I'm basically trying to do the former, where I access the text via the `children` variable. This one variable contains the text for all of the items with expandable menus, and I'm not sure how to separate out and get the specific block of text that I need out of it. Does that make sense?

**Comment by seankwilliams** [comment]
@kmid5280 That makes sense. Where are you trying to access the variable from? It would be accessible from within the `ShowBuilderItem` component (it's available from the component's props). Otherwise, the `children` variable is the HTML that is passed as inner HTML to `ShowBuilderItem` - in other words, what comes in between the `<ShowBuilderItem>` and `</ShowBuilderItem>` tags.

**Comment by kmid5280** [comment]
@seankwilliams I played with it and pushed a new commit. The new code adds a clipboard icon (as yet not correctly positioned), which will only display if there are additional show details. Currently it will copy the text, though it is not yet removing extraneous HTML tags, quotation marks, etc.. I will want to fine tune this to be able to clear that out. In the meanwhile, how does this look so far? I think I was able to access the inner HTML, but I can't help but think there is a more eloquent way to do it than the way I did it (i.e., using `children[0].props`).

**Comment by seankwilliams** [comment]
@kmid5280 There may be a cleaner way to do it, but I'm not sure what that would be without spending some time going through it. If that code is working, then this is good! When cleaning out the content, ideally it should work as close to a copy & paste from the browser as possible. Sometimes that does bring some formatting over to other programs (like if you paste from a browser into Word, for example). So let's try to match that behavior, but if it's too much effort, stripping out the HTML tags is fine.

**Comment by kmid5280** [comment]
@seankwilliams I imported and used the stripHtml method, and added some additional filters to get rid of some of the extraneous tags and quotations marks and things. It seems to work pretty well so far, though it's possible I may have missed some things to filter. The question now is where to position the icon. It seems to default to the lower left corner, which could be fine. Otherwise we could attempt to reposition it.

**Comment by seankwilliams** [comment]
@kmid5280 That's looking good so far. Can you make it so the icon is in the upper right corner of the description area? Also, can you give the element a title attribute of `Copy text to clipboard` so that a tooltip appears when hovering over the icon? And, please add CSS of `cursor: pointer;` to the icon as well so users will know it's clickable.
