### ISSUE TITLE
API token creation/deletion interface

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#71]
Should display the last time an API token was used.

Zendesk has a nice API that we could go off of for inspiration.

**Comment by dzimmerman902** [comment]
@seankwilliams This should be done, you can check it out by viewing each users profile. Make sure to log in for it to work, needs a role === 'Admin' to view API functionality.

**Comment by seankwilliams** [comment]
@dzimmerman902 Looks great, nice work!
