### ISSUE TITLE
RichTextArea component's custom toolbar does not render properly in all cases

### ISSUE THREAD

**Issue by kmid5280** [codefordenver/Comrad#735]
## Description of Issue

Some instances of the RichTextArea component do not render correctly. For example, from the landing page -> My Past Shows -> Edit Show Instance, will bring up the edit screen. The custom toolbar does not render properly in the description box:

<img width="395" alt="screen1" src="https://user-images.githubusercontent.com/35879775/144940514-ffce9b4c-7891-4e0f-bf3d-1147fe690b3a.png">

The functionality of the buttons is also lost here. Compare this with the RichTextArea component on the ShowBuilder page. Click an individual show, then click the comment tab, and we get this:

<img width="371" alt="screen2" src="https://user-images.githubusercontent.com/35879775/144940617-2ae7c551-5ee9-473d-b830-a036d94e94db.png">

So far have tried changing the `className` attribute of the Field component containing the RichTextArea. Have also tried changing the `type` attribute. Since the toolbar renders correctly in some cases, the issue is likely not with React-Quill itself.

**Comment by kmid5280** [comment]
@seankwilliams Closing issue. Issue not visible on test site. Still shows up locally even after updating packages.

**Comment by seankwilliams** [comment]
Thanks @kmid5280 !
