### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by JJK1231** [codefordenver/Comrad#767]
## Description of Issue

Actually nothing works at all. The server and client have started up, but that's about it. I can't log in because I don't have login details. localhost:3000/admin works, but everything keeps loading continuously to no avail. I don't really know where to look for it. I am working with Ubuntu 20.04

If you want, you can take a look:
http://cloud.jeremydekamper.nl:3000/admin

**Comment by seankwilliams** [comment]
Got this resolved working with @JJK1231 directly. Created documentation for new server setup at https://github.com/codefordenver/Comrad/blob/development/docs/production_server_setup.md to help people with this in the future.
