### ISSUE TITLE
Show Builder UX change: clear search box after a result is added to saved items or scratchpad

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#830]
On Show Builder, after an item is added to saved items or scratchpad, the search box should clear.

**Comment by themachinelearner** [comment]
Hey Sean, I can take a look at this. LMK if there is a different method for grabbing issues.

**Comment by seankwilliams** [comment]
That would be great, thank you @themachinelearner ! Let me know if you need any help getting a local dev environment up and running.

**Comment by themachinelearner** [comment]
@seankwilliams Just submitted a pull request. Feel free to suggest edits if needed.

**Comment by seankwilliams** [comment]
The pull request looks great. Thanks @themachinelearner ! I'll merge that to main and deploy that to the site.

**Comment by seankwilliams** [comment]
resolved by https://github.com/codefordenver/Comrad/pull/854
