### ISSUE TITLE
Padding issue in Add Traffic description box

### ISSUE THREAD

**Issue by kmid5280** [codefordenver/Comrad#887]
## Description of Issue

It looks like the description box in the Add Traffic form could use additional padding.

## Possible Solution and/or Approach

We could change the padding value for the `.ql-editor` attribute in the RichTextArea scss file, though this would affect all pages where the RichTextArea component is used.

<img width="382" alt="traffic-add-desc" src="https://github.com/codefordenver/Comrad/assets/35879775/e7ecc79d-b426-417e-b682-a2a06d8583db">

**Comment by seankwilliams** [comment]
@kmid5280 Are you referring to the padding between the edges of the box and the text itself? If so, feel free to change the styles globally with whatever you think looks best.
