### ISSUE TITLE
UX change on Show Builder page

### ISSUE THREAD

**Issue by seankwilliams** [codefordenver/Comrad#893]
Let's make the 'edit show description' text larger on the showbuilder pages, making it more prominent for DJs, and maybe moving it under the show title too, if it fits?

**Comment by seankwilliams** [comment]
@kmid5280 This request came through from KGNU. Would you be able to take a look?

**Comment by kmid5280** [comment]
@seankwilliams Sure I can look at it. Do we want it about the same size as the show title?
<img width="833" alt="showdesc" src="https://github.com/codefordenver/Comrad/assets/35879775/c8492280-baba-4309-ac20-959b51ad6a81">

**Comment by seankwilliams** [comment]
@kmid5280 Sure, let's do that!

**Comment by kmid5280** [comment]
@seankwilliams I made a PR, let me know how this looks.
